#! /bin/sh


## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"
export XDG_CURRENT_DESKTOP='bspwm'

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D


## Current theme -----------------------------------------------

# Bspwm colors
BSPWM_FBC='#81A1C1'
BSPWM_NBC='#2E3440'
BSPWM_ABC='#B48EAD'
BSPWM_PFC='#A3BE8C'



## Manage Monitors and Workspaces ------------------------------

# Creating workspace
if xrandr -q | grep -q "HDMI-1 connected"; then
    bspc monitor "HDMI-1" -d '' '' '' '' 
    bspc monitor "eDP-1" -d '' '' '' ''
    bspc wm -O "HDMI-1" "eDP-1"
else
    bspc monitor "eDP-1" -d '' '' '' '' '' '' '' ''
fi


# BSPWM Configuration
bspc config border_width        2
bspc config window_gap          10
bspc config split_ratio         0.50

bspc config focused_border_color  "$BSPWM_FBC"
bspc config normal_border_color   "$BSPWM_NBC"
bspc config active_border_color   "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

# Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans



## Window rules ------------------------------------------------

# xprop to find app name
# reset all rules first
bspc rule -a Screenkey manage=off
## remove all rules first
bspc rule -r *:*

## 1 > terminal
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a Xfce4-terminal desktop='^1' follow=on focus=on

## 2 > code
declare -a code=(code-oss neovim arduino-ide)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done

## 3 > web
bspc rule -a firefox desktop='^3' follow=on focus=on

## 4 > files
declare -a files=(Pcmanfm Thunar qBittorrent)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

## 5 > office and docs
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice onlyoffice-desktopeditors)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

## 6 > communication
bspc rule -a warpinator desktop='^6' follow=on focus=on
bspc rule -a thunderbird desktop='^6' follow=on focus=on
bspc rule -a discord desktop='^6' follow=on focus=on
# Don't follow when discord opens
bspc rule -a discord:discord state=floating follow=off window_type=dialog

## 7 > media
declare -a media=(Audacity Deezer Music MPlayerc Inkscape Gimp)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done

## 8 > system
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings 'VirtualBox Manager' Gparted)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done
# Open htop and ranger
bspc rule -a AlacrittyOverrideUtils desktop='^8' follow=on focus=on




## Always Floating Apps
declare -a floating=(alacritty-float Pcmanfm Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor calamares Calamares)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off



# OnStart apps -------------------------------------------------
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr
exec mpd & 

## xrandr ... --same-as to copy screen
xrandr --output eDP-1 --scale 1.1 \
  --output HDMI-1 --scale 1.0 --left-of eDP-1
picom -b
feh --randomize --bg-scale /usr/share/backgrounds/*
# Make Super_L open rofi_launcher when tapped alone
xcape -e 'Super_L=Alt_L|F1' &
xcape -e 'Super_R=Alt_L|F1' &
# Enable power management
xfce4-power-manager &
# Notification daemon
dunst &

